# Generated by Django 3.2.4 on 2022-07-11 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0004_alter_robot_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trained_attribute', models.CharField(choices=[('strength', 'STRENGTH'), ('speed', 'SPEED'), ('skill', 'SKILL'), ('defense', 'DEFENSE')], max_length=16, verbose_name='Atributo treinado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Data da última mudança')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
    ]
