# Generated by Django 3.2.4 on 2022-07-07 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy', models.FloatField(editable=False, verbose_name='Energia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Data da última mudança')),
                ('color_energy', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarelo')], max_length=16, verbose_name='Cor da Barra de Energia')),
                ('class_robot', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender'), ('tricker', 'Tricker'), ('mechanical', 'Mechanical')], max_length=16, verbose_name='Classe')),
                ('color_robot', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('red', 'Red')], max_length=16, verbose_name='Cor do robô')),
                ('strength', models.FloatField(verbose_name='Força')),
                ('speed', models.FloatField(verbose_name='Velocidade')),
                ('skill', models.FloatField(verbose_name='Habilidade')),
                ('defense', models.FloatField(verbose_name='Defesa')),
            ],
            options={
                'verbose_name': 'Robô',
                'verbose_name_plural': 'Robôs',
            },
        ),
    ]
