# Generated by Django 3.2.4 on 2022-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='energy',
            field=models.FloatField(verbose_name='Energia'),
        ),
    ]
