# Generated by Django 3.2.4 on 2022-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_alter_robot_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='energy',
            field=models.FloatField(default=5.0, verbose_name='Energia'),
        ),
    ]
