# Generated by Django 3.2.4 on 2022-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_join_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestjointeam',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requested', max_length=16, verbose_name='Status'),
        ),
    ]
