# Generated by Django 3.2.4 on 2022-07-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_join_team', '0002_alter_requestjointeam_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestjointeam',
            options={'verbose_name': 'Pedido para entrar em time', 'verbose_name_plural': 'Pedidos para entrar em time'},
        ),
    ]
