# Generated by Django 3.2.4 on 2022-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to='robots.Robot'),
        ),
    ]
