# Generated by Django 3.2.4 on 2022-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_alter_robot_energy'),
        ('teams', '0004_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='robots.Robot'),
        ),
    ]
