# Generated by Django 3.2.4 on 2022-07-07 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_alter_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Data da última mudança')),
                ('first_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_team', to='teams.team')),
                ('second_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_team', to='teams.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='teams.team')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
